### ISSUE TITLE
Download and upload POS Control 

### ISSUE THREAD

**Issue by ShadAhm** [ShadAhm/AMPOS#10]
Download POS_Control if it is empty upon startup.
Upload POS Control on upload data.

**Comment by eddiewgj** [comment]
Download POS_Control table if it is empty by Company, Outlet and POS Number. 
Upload POS_Control table to HQ when perform Upload.

**Comment by ShadAhm** [comment]
Pushed in commit 0d3a229130a9652238d316a710efbba51164f3a3.

Build passing but not tested.

@eddiewgj

**Comment by ShadAhm** [comment]
Fixed and tested in commit 7c995aaf5f19d8cb8e539ab81c8d1298e9ddb5c9 over TeamViewer

**Comment by eddiewgj** [comment]
Tested working on 23/12/2016.
