### ISSUE TITLE
Row number for detail table is reset when combine with suspend

### ISSUE THREAD

**Issue by eddiewgj** [ShadAhm/AMPOS#9]
Row number for detail table is reset when combine with suspend

**Comment by ShadAhm** [comment]
Fixed this issue in commit b41f45a5355a50b6aa8c50c4f6776cb14e9a3cd2.

Waiting to be tested.

**Comment by ShadAhm** [comment]
Fixed and tested in commit 7c995aaf5f19d8cb8e539ab81c8d1298e9ddb5c9

**Comment by eddiewgj** [comment]
Tested working on 23/12/2016.
